### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

### Logout
DELETE http://localhost:8000/api/logout
Content-Type: application/json
Authorization: Bearer TOKEN
