### Login
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "jann.kowalski@test.pl",
    "password": "test1234"
}

### Logout
DELETE http://localhost:8000/api/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer TOKEN
