### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "mccullough.emily@example.org",
    "password": "password"
}

### Logout
POST http://localhost:8000/api/logout
Content-Type: application/json
Authorization: Bearer TOKEN
