### Show all passwords
GET http://localhost:8000/api/passwords/
Content-Type: application/json
Authorization: Bearer TOKEN

### Show password
GET http://localhost:8000/api/passwords/id
Content-Type: application/json
Authorization: Bearer TOKEN

### Create password
POST http://localhost:8000/api/passwords/
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "name": "password name",
    "password": "password"
}

### Update password
PUT http://localhost:8000/api/passwords/id
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "name": "password name",
    "password": "password"
}

### Delete password
DELETE http://localhost:8000/api/passwords/id
Content-Type: application/json
Authorization: Bearer TOKEN
