### Show all passwords
GET http://localhost:8000/api/passwords/
Accept: application/json
Authorization: Bearer TOKEN

### Show all passwords for admin
GET http://localhost:8000/api/passwords-admin/
Accept: application/json
Authorization: Bearer TOKEN

### Show password
GET http://localhost:8000/api/passwords/3
Accept: application/json
Authorization: Bearer 1|cELUlvZ8FsgJ1HQ8HrqxyGpR33828JGHUrfVuKHB

### Create password
POST http://localhost:8000/api/passwords/
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cELUlvZ8FsgJ1HQ8HrqxyGpR33828JGHUrfVuKHB

//    "type": "application",
//    "url": "http://example.com",

{
    "name": "password name",
    "type": "sshftp",
    "host": "example.com",
    "port": 22,
    "username": "user",
    "password": "password"
}

### Update password
PUT http://localhost:8000/api/passwords/id
Content-Type: application/json
Accept: application/json
Authorization: Bearer TOKEN

{
    "name": "password name",
    "password": "password"
}

### Delete password
DELETE http://localhost:8000/api/passwords/62
Accept: application/json
Authorization: Bearer TOKEN
