### Show all users
GET http://localhost:8000/api/users/
Content-Type: application/json

### Show user
GET http://localhost:8000/api/users/id
Content-Type: application/json

### Create new user
POST http://localhost:8000/api/users/
Content-Type: application/json

{
  "name": "Jan",
  "last_name": "Kowalski",
  "password": "test1234",
  "email": "jan.kowalski@test.pl"
}

### Update user
PUT http://localhost:8000/api/users/id
Content-Type: application/json

{
  "name": "Jan",
  "last_name": "Kowalski",
  "password": "test1234",
  "email": "jan.kowalski@test.pl",
  "is_admin": true
}

### Delete user
DELETE http://localhost:8000/api/users/id
Content-Type: application/json
